// src/lead-item/schema/lead-item.schema.ts

import { z } from 'zod';

/**
 * Base Zod schema for the LeadItem model.
 * This is the single source of truth for validation rules.
 */
export const leadItemSchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1, { message: 'Lead item name cannot be empty' }),
  description: z.string().optional().nullable(),
  agentId: z.string().uuid({ message: 'Invalid agent ID' }),
  createdAt: z.date(),
  updatedAt: z.date(),
});

/**
 * Schema for creating a new lead item.
 * Omits fields that are auto-generated by the database.
 */
export const createLeadItemSchema = leadItemSchema.omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

/**
 * Schema for updating an existing lead item.
 * All fields are made optional for partial updates.
 */
export const updateLeadItemSchema = createLeadItemSchema.partial();
